"""empty message

Revision ID: 006ad18c718d
Revises: 02fc8d5697b4
Create Date: 2023-11-28 21:42:03.586947

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '006ad18c718d'
down_revision = '02fc8d5697b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('amountearned',
    sa.Column('earning_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('amounts_earned', sa.String(length=120), nullable=True),
    sa.Column('earning_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('earning_id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('user_address',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('user_address',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)

    op.drop_table('amountearned')
    # ### end Alembic commands ###
