"""empty message

Revision ID: bf86599bcd7e
Revises: 006ad18c718d
Create Date: 2023-11-29 08:05:47.861448

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bf86599bcd7e'
down_revision = '006ad18c718d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cart_owner', sa.String(length=200), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['cart_owner'], ['user_address'])

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('ordered_byaddress',
               existing_type=mysql.VARCHAR(length=120),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'user', ['ordered_byaddress'], ['user_address'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('user_address',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('user_address',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('ordered_byaddress',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=120),
               existing_nullable=True)

    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('cart_owner')

    # ### end Alembic commands ###
